In [8]:
import numpy as np

In [95]:
#numpy reshaping
arr = np.array([25,26,37,65,78,89,93,74,76,77,86,84,80,69,15,16,17,18,19,20,21,22,23,24,25])
arr = arr.reshape(5,5)
print(arr)
array1 = arr.reshape((25,))
print(array1)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
array2 = arr[arr > 50]
print(array2)


[[25 26 37 65 78]
 [89 93 74 76 77]
 [86 84 80 69 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[25 26 37 65 78 89 93 74 76 77 86 84 80 69 15 16 17 18 19 20 21 22 23 24
 25]
93
15
47.16
[65 78 89 93 74 76 77 86 84 80 69]


In [4]:
import pandas as pd 
from datetime import datetime
# Data for the DataFrame
s6 = {
    'Name': ['Francis', 'Egah', 'David', 'Michael', 'obi', 'James', 'Emma', 'Abraham', 'Isa', 'Chris'],
    'Age': [28, 34, 26, 45, 39, 30, 32, 50, 29, 42],
    'Salary': [5000, 6000, 52000, 70000, 58000, 54000, 56000, 80000, 53000, 65000],
    'Department': ['HR', 'Engineering', 'Marketing', 'Finance', 'IT', 'Sales', 'HR', 'Engineering', 'Marketing', 'Finance'],
    'Date of Joining': ['2019-01-15', '2018-03-22', '2020-07-18', '2017-09-10', '2016-11-05', '2018-06-28', '2019-08-12', '2015-12-30', '2021-05-14', '2017-04-25']
}
# Create the DataFrame
arr = pd.DataFrame(s6)


print(arr)


      Name  Age  Salary   Department Date of Joining
0  Francis   28    5000           HR      2019-01-15
1     Egah   34    6000  Engineering      2018-03-22
2    David   26   52000    Marketing      2020-07-18
3  Michael   45   70000      Finance      2017-09-10
4      obi   39   58000           IT      2016-11-05
5    James   30   54000        Sales      2018-06-28
6     Emma   32   56000           HR      2019-08-12
7  Abraham   50   80000  Engineering      2015-12-30
8      Isa   29   53000    Marketing      2021-05-14
9    Chris   42   65000      Finance      2017-04-25


In [55]:

average_salary_per_department = arr.groupby('Department')['Salary'].mean()

print(average_salary_per_department)


Department
Engineering    43000.0
Finance        67500.0
HR             30500.0
IT             58000.0
Marketing      52500.0
Sales          54000.0
Name: Salary, dtype: float64


In [12]:
import pandas as pd 
from datetime import datetime
current_date = datetime.now()
arr['Years in Company'] = arr['Date of Joining'].apply(lambda x: current_date.year - pd.to_datetime(x).year)
print(arr)

      Name  Age  Salary   Department Date of Joining  Years in Company
0  Francis   28    5000           HR      2019-01-15                 5
1     Egah   34    6000  Engineering      2018-03-22                 6
2    David   26   52000    Marketing      2020-07-18                 4
3  Michael   45   70000      Finance      2017-09-10                 7
4      obi   39   58000           IT      2016-11-05                 8
5    James   30   54000        Sales      2018-06-28                 6
6     Emma   32   56000           HR      2019-08-12                 5
7  Abraham   50   80000  Engineering      2015-12-30                 9
8      Isa   29   53000    Marketing      2021-05-14                 3
9    Chris   42   65000      Finance      2017-04-25                 7


In [91]:
filtered_arr = arr[arr['Years in Company'] > 5]
print(filtered_arr)

      Name  Age  Salary   Department Date of Joining  Years in Company
1     Egah   34    6000  Engineering      2018-03-22                 6
3  Michael   45   70000      Finance      2017-09-10                 7
4      obi   39   58000           IT      2016-11-05                 8
5    James   30   54000        Sales      2018-06-28                 6
7  Abraham   50   80000  Engineering      2015-12-30                 9
9    Chris   42   65000      Finance      2017-04-25                 7
